# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projetos\Kiriki\Client\src\GUI\Game.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 500)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: #c7c7c7;\n"
"}\n"
"\n"
"QLabel{\n"
"    font-size:28px;\n"
"    font-family:Calibri;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    font-size:28px;\n"
"    font-family:Calibri;\n"
"    padding: 15px 25px;\n"
"      text-align: center;    \n"
"      text-decoration: none;\n"
"      outline: none;\n"
"      border: 1px solid black;\n"
"      border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"#sumValueLabel {\n"
"    font-size:40px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gameNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.gameNameLabel.setGeometry(QtCore.QRect(760, 450, 131, 50))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(-1)
        self.gameNameLabel.setFont(font)
        self.gameNameLabel.setStyleSheet("#gameNameLabel {\n"
"    font-size: 45px;\n"
"    font-family:Algerian;\n"
"}")
        self.gameNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gameNameLabel.setObjectName("gameNameLabel")
        self.slotC = QtWidgets.QLabel(self.centralwidget)
        self.slotC.setGeometry(QtCore.QRect(429, 336, 31, 41))
        self.slotC.setText("")
        self.slotC.setPixmap(QtGui.QPixmap(":/newPrefix/DiceSlot.png"))
        self.slotC.setObjectName("slotC")
        self.playerCup = QtWidgets.QLabel(self.centralwidget)
        self.playerCup.setGeometry(QtCore.QRect(373, 288, 141, 133))
        self.playerCup.setText("")
        self.playerCup.setPixmap(QtGui.QPixmap(":/newPrefix/playerCup.png"))
        self.playerCup.setObjectName("playerCup")
        self.slotS = QtWidgets.QLabel(self.centralwidget)
        self.slotS.setGeometry(QtCore.QRect(429, 378, 31, 41))
        self.slotS.setText("")
        self.slotS.setPixmap(QtGui.QPixmap(":/newPrefix/DiceSlot.png"))
        self.slotS.setObjectName("slotS")
        self.slotW = QtWidgets.QLabel(self.centralwidget)
        self.slotW.setGeometry(QtCore.QRect(383, 336, 31, 41))
        self.slotW.setText("")
        self.slotW.setPixmap(QtGui.QPixmap(":/newPrefix/DiceSlot.png"))
        self.slotW.setObjectName("slotW")
        self.slotN = QtWidgets.QLabel(self.centralwidget)
        self.slotN.setGeometry(QtCore.QRect(429, 293, 31, 41))
        self.slotN.setText("")
        self.slotN.setPixmap(QtGui.QPixmap(":/newPrefix/DiceSlot.png"))
        self.slotN.setObjectName("slotN")
        self.slotE = QtWidgets.QLabel(self.centralwidget)
        self.slotE.setGeometry(QtCore.QRect(475, 336, 31, 41))
        self.slotE.setText("")
        self.slotE.setPixmap(QtGui.QPixmap(":/newPrefix/DiceSlot.png"))
        self.slotE.setObjectName("slotE")
        self.slotNNumber = QtWidgets.QLabel(self.centralwidget)
        self.slotNNumber.setGeometry(QtCore.QRect(440, 306, 16, 16))
        self.slotNNumber.setText("")
        self.slotNNumber.setObjectName("slotNNumber")
        self.slotENumber = QtWidgets.QLabel(self.centralwidget)
        self.slotENumber.setGeometry(QtCore.QRect(486, 348, 16, 16))
        self.slotENumber.setText("")
        self.slotENumber.setObjectName("slotENumber")
        self.slotWNumber = QtWidgets.QLabel(self.centralwidget)
        self.slotWNumber.setGeometry(QtCore.QRect(394, 348, 16, 16))
        self.slotWNumber.setText("")
        self.slotWNumber.setObjectName("slotWNumber")
        self.slotCNumber = QtWidgets.QLabel(self.centralwidget)
        self.slotCNumber.setGeometry(QtCore.QRect(440, 349, 16, 16))
        self.slotCNumber.setText("")
        self.slotCNumber.setObjectName("slotCNumber")
        self.slotSNumber = QtWidgets.QLabel(self.centralwidget)
        self.slotSNumber.setGeometry(QtCore.QRect(440, 390, 16, 16))
        self.slotSNumber.setText("")
        self.slotSNumber.setObjectName("slotSNumber")
        self.userNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.userNameLabel.setGeometry(QtCore.QRect(310, 430, 271, 31))
        self.userNameLabel.setText("")
        self.userNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.userNameLabel.setObjectName("userNameLabel")
        self.opponentCup = QtWidgets.QLabel(self.centralwidget)
        self.opponentCup.setGeometry(QtCore.QRect(373, 50, 151, 141))
        self.opponentCup.setText("")
        self.opponentCup.setPixmap(QtGui.QPixmap(":/newPrefix/opponentCup.png"))
        self.opponentCup.setObjectName("opponentCup")
        self.opponentNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.opponentNameLabel.setGeometry(QtCore.QRect(310, 10, 271, 31))
        self.opponentNameLabel.setText("")
        self.opponentNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.opponentNameLabel.setObjectName("opponentNameLabel")
        self.opponentCurrentDiceNumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.opponentCurrentDiceNumberLabel.setGeometry(QtCore.QRect(417, 91, 61, 61))
        self.opponentCurrentDiceNumberLabel.setStyleSheet("#opponentCurrentDiceNumberLabel{\n"
"    font-size:55px;\n"
"}")
        self.opponentCurrentDiceNumberLabel.setText("")
        self.opponentCurrentDiceNumberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.opponentCurrentDiceNumberLabel.setObjectName("opponentCurrentDiceNumberLabel")
        self.sumScreen = QtWidgets.QLabel(self.centralwidget)
        self.sumScreen.setGeometry(QtCore.QRect(91, 60, 211, 91))
        self.sumScreen.setText("")
        self.sumScreen.setPixmap(QtGui.QPixmap(":/newPrefix/SumScreen.png"))
        self.sumScreen.setObjectName("sumScreen")
        self.sumTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.sumTitleLabel.setGeometry(QtCore.QRect(100, 43, 201, 41))
        self.sumTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sumTitleLabel.setObjectName("sumTitleLabel")
        self.gessTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.gessTitleLabel.setGeometry(QtCore.QRect(90, 270, 201, 41))
        self.gessTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gessTitleLabel.setObjectName("gessTitleLabel")
        self.sendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sendBtn.setGeometry(QtCore.QRect(40, 412, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.sendBtn.setFont(font)
        self.sendBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendBtn.setStyleSheet("#sendBtn {\n"
"  display: inline-block;\n"
"  padding: 15px 25px;\n"
"  font-size: 28px;\n"
"  font-family: Calibri;\n"
"  text-align: center;    \n"
"  text-decoration: none;\n"
"  outline: none;\n"
"  color: #fff;\n"
"  background-color: #70ad46;\n"
"  border: none;\n"
"  border-radius: 15px;\n"
"}\n"
"\n"
"#sendBtn[enabled=\"false\"] {\n"
"  display: inline-block;\n"
"  padding: 15px 25px;\n"
"  font-size: 28px;\n"
"  font-family: Calibri;\n"
"  text-align: center;    \n"
"  text-decoration: none;\n"
"  outline: none;\n"
"  color: #fff;\n"
"  background-color: #a0a0a0;\n"
"  border: none;\n"
"  border-radius: 15px;\n"
"}\n"
"\n"
"#sendBtn:hover {\n"
"background-color: #3e8e41\n"
"}\n"
"\n"
"#sendBtn:pressed {\n"
"  background-color: #4CAF50;\n"
"}\n"
"")
        self.sendBtn.setObjectName("sendBtn")
        self.input0 = QtWidgets.QLineEdit(self.centralwidget)
        self.input0.setGeometry(QtCore.QRect(41, 314, 45, 80))
        self.input0.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.input0.setObjectName("input0")
        self.input1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input1.setGeometry(QtCore.QRect(105, 314, 45, 80))
        self.input1.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.input1.setObjectName("input1")
        self.input2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input2.setGeometry(QtCore.QRect(169, 314, 45, 80))
        self.input2.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.input2.setObjectName("input2")
        self.input3 = QtWidgets.QLineEdit(self.centralwidget)
        self.input3.setGeometry(QtCore.QRect(233, 314, 45, 80))
        self.input3.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.input3.setObjectName("input3")
        self.input4 = QtWidgets.QLineEdit(self.centralwidget)
        self.input4.setGeometry(QtCore.QRect(297, 314, 45, 80))
        self.input4.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.input4.setObjectName("input4")
        self.sumContainer = QtWidgets.QWidget(self.centralwidget)
        self.sumContainer.setGeometry(QtCore.QRect(100, 90, 201, 71))
        self.sumContainer.setStyleSheet("#sumContainer {\n"
"    background-color: #fff;\n"
"    padding: 15px 25px;\n"
"      border: 1px solid blue;\n"
"      border-radius: 10px;\n"
"}\n"
"")
        self.sumContainer.setObjectName("sumContainer")
        self.sumValueLabel = QtWidgets.QLabel(self.sumContainer)
        self.sumValueLabel.setGeometry(QtCore.QRect(0, 0, 201, 71))
        self.sumValueLabel.setStyleSheet("")
        self.sumValueLabel.setText("")
        self.sumValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sumValueLabel.setObjectName("sumValueLabel")
        self.msgTitle = QtWidgets.QLabel(self.centralwidget)
        self.msgTitle.setGeometry(QtCore.QRect(560, 233, 331, 41))
        self.msgTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.msgTitle.setObjectName("msgTitle")
        self.msgContainer = QtWidgets.QWidget(self.centralwidget)
        self.msgContainer.setGeometry(QtCore.QRect(560, 270, 331, 151))
        self.msgContainer.setStyleSheet("#msgContainer {\n"
"    background-color: #fff;\n"
"    padding: 15px 25px;\n"
"      border: 1px solid black;\n"
"      border-radius: 10px;\n"
"}\n"
"")
        self.msgContainer.setObjectName("msgContainer")
        self.msgLabel = QtWidgets.QLabel(self.msgContainer)
        self.msgLabel.setGeometry(QtCore.QRect(10, 10, 321, 141))
        self.msgLabel.setStyleSheet("")
        self.msgLabel.setText("")
        self.msgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.msgLabel.setObjectName("msgLabel")
        self.opponentInputContainer0 = QtWidgets.QWidget(self.centralwidget)
        self.opponentInputContainer0.setGeometry(QtCore.QRect(560, 85, 45, 80))
        self.opponentInputContainer0.setStyleSheet("#opponentInputContainer0{\n"
"    background-color: #fff;\n"
"    padding: 15px 25px;\n"
"      border: 1px solid black;\n"
"      border-radius: 10px;\n"
"}\n"
"")
        self.opponentInputContainer0.setObjectName("opponentInputContainer0")
        self.opponentInput0Label = QtWidgets.QLabel(self.opponentInputContainer0)
        self.opponentInput0Label.setGeometry(QtCore.QRect(2, 0, 41, 81))
        self.opponentInput0Label.setStyleSheet("")
        self.opponentInput0Label.setText("")
        self.opponentInput0Label.setAlignment(QtCore.Qt.AlignCenter)
        self.opponentInput0Label.setObjectName("opponentInput0Label")
        self.opponentInputContainer1 = QtWidgets.QWidget(self.centralwidget)
        self.opponentInputContainer1.setGeometry(QtCore.QRect(620, 85, 45, 80))
        self.opponentInputContainer1.setStyleSheet("#opponentInputContainer1{\n"
"    background-color: #fff;\n"
"    padding: 15px 25px;\n"
"      border: 1px solid black;\n"
"      border-radius: 10px;\n"
"}\n"
"")
        self.opponentInputContainer1.setObjectName("opponentInputContainer1")
        self.opponentInput1Label = QtWidgets.QLabel(self.opponentInputContainer1)
        self.opponentInput1Label.setGeometry(QtCore.QRect(2, 0, 41, 81))
        self.opponentInput1Label.setStyleSheet("")
        self.opponentInput1Label.setText("")
        self.opponentInput1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.opponentInput1Label.setObjectName("opponentInput1Label")
        self.opponentInputContainer2 = QtWidgets.QWidget(self.centralwidget)
        self.opponentInputContainer2.setGeometry(QtCore.QRect(680, 85, 45, 80))
        self.opponentInputContainer2.setStyleSheet("#opponentInputContainer2{\n"
"    background-color: #fff;\n"
"    padding: 15px 25px;\n"
"      border: 1px solid black;\n"
"      border-radius: 10px;\n"
"}\n"
"")
        self.opponentInputContainer2.setObjectName("opponentInputContainer2")
        self.opponentInput2Label = QtWidgets.QLabel(self.opponentInputContainer2)
        self.opponentInput2Label.setGeometry(QtCore.QRect(2, 0, 41, 81))
        self.opponentInput2Label.setStyleSheet("")
        self.opponentInput2Label.setText("")
        self.opponentInput2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.opponentInput2Label.setObjectName("opponentInput2Label")
        self.opponentInputContainer3 = QtWidgets.QWidget(self.centralwidget)
        self.opponentInputContainer3.setGeometry(QtCore.QRect(740, 85, 45, 80))
        self.opponentInputContainer3.setStyleSheet("#opponentInputContainer3{\n"
"    background-color: #fff;\n"
"    padding: 15px 25px;\n"
"      border: 1px solid black;\n"
"      border-radius: 10px;\n"
"}\n"
"")
        self.opponentInputContainer3.setObjectName("opponentInputContainer3")
        self.opponentInput3Label = QtWidgets.QLabel(self.opponentInputContainer3)
        self.opponentInput3Label.setGeometry(QtCore.QRect(2, 0, 41, 81))
        self.opponentInput3Label.setStyleSheet("")
        self.opponentInput3Label.setText("")
        self.opponentInput3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.opponentInput3Label.setObjectName("opponentInput3Label")
        self.opponentInputContainer4 = QtWidgets.QWidget(self.centralwidget)
        self.opponentInputContainer4.setGeometry(QtCore.QRect(800, 85, 45, 80))
        self.opponentInputContainer4.setStyleSheet("#opponentInputContainer4{\n"
"    background-color: #fff;\n"
"    padding: 15px 25px;\n"
"      border: 1px solid black;\n"
"      border-radius: 10px;\n"
"}\n"
"")
        self.opponentInputContainer4.setObjectName("opponentInputContainer4")
        self.opponentInput4Label = QtWidgets.QLabel(self.opponentInputContainer4)
        self.opponentInput4Label.setGeometry(QtCore.QRect(2, 0, 41, 81))
        self.opponentInput4Label.setStyleSheet("")
        self.opponentInput4Label.setText("")
        self.opponentInput4Label.setAlignment(QtCore.Qt.AlignCenter)
        self.opponentInput4Label.setObjectName("opponentInput4Label")
        self.sumTitleLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.sumTitleLabel_2.setGeometry(QtCore.QRect(560, 40, 281, 41))
        self.sumTitleLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sumTitleLabel_2.setObjectName("sumTitleLabel_2")
        self.gameNameLabel.raise_()
        self.playerCup.raise_()
        self.slotS.raise_()
        self.slotW.raise_()
        self.slotN.raise_()
        self.slotE.raise_()
        self.slotC.raise_()
        self.slotNNumber.raise_()
        self.slotENumber.raise_()
        self.slotWNumber.raise_()
        self.slotCNumber.raise_()
        self.slotSNumber.raise_()
        self.userNameLabel.raise_()
        self.opponentCup.raise_()
        self.opponentNameLabel.raise_()
        self.opponentCurrentDiceNumberLabel.raise_()
        self.sumScreen.raise_()
        self.sumTitleLabel.raise_()
        self.gessTitleLabel.raise_()
        self.sendBtn.raise_()
        self.input0.raise_()
        self.input1.raise_()
        self.input2.raise_()
        self.input3.raise_()
        self.input4.raise_()
        self.sumContainer.raise_()
        self.msgTitle.raise_()
        self.msgContainer.raise_()
        self.opponentInputContainer0.raise_()
        self.opponentInputContainer1.raise_()
        self.opponentInputContainer2.raise_()
        self.opponentInputContainer3.raise_()
        self.opponentInputContainer4.raise_()
        self.sumTitleLabel_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kiriki"))
        self.gameNameLabel.setText(_translate("MainWindow", "Kiriki"))
        self.sumTitleLabel.setText(_translate("MainWindow", "Soma"))
        self.gessTitleLabel.setText(_translate("MainWindow", "Aposta"))
        self.sendBtn.setText(_translate("MainWindow", "ENVIAR"))
        self.msgTitle.setText(_translate("MainWindow", "Mensagens"))
        self.sumTitleLabel_2.setText(_translate("MainWindow", "Última Aposta"))
from src.GUI.images import Config_rc
