# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projetos\Kiriki\Client\src\GUI\Game.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 500)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: #c7c7c7;\n"
"}\n"
"\n"
"QLabel{\n"
"    font-size:28px;\n"
"    font-family:Calibri;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    font-size:28px;\n"
"    font-family:Calibri;\n"
"      text-align: center;    \n"
"      border: 1px solid black;\n"
"      border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"#sumValueLabel {\n"
"    font-size:40px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #fff;\n"
"      border: 1px solid black;\n"
"      border-radius: 4px;\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gameNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.gameNameLabel.setGeometry(QtCore.QRect(760, 450, 131, 50))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(-1)
        self.gameNameLabel.setFont(font)
        self.gameNameLabel.setStyleSheet("#gameNameLabel {\n"
"    font-size: 45px;\n"
"    font-family:Algerian;\n"
"}")
        self.gameNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gameNameLabel.setObjectName("gameNameLabel")
        self.playerCup = QtWidgets.QLabel(self.centralwidget)
        self.playerCup.setGeometry(QtCore.QRect(373, 288, 141, 133))
        self.playerCup.setText("")
        self.playerCup.setPixmap(QtGui.QPixmap(":/newPrefix/playerCup.png"))
        self.playerCup.setObjectName("playerCup")
        self.slotNNumber = QtWidgets.QLabel(self.centralwidget)
        self.slotNNumber.setGeometry(QtCore.QRect(436, 307, 16, 16))
        self.slotNNumber.setText("")
        self.slotNNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.slotNNumber.setProperty("value", "")
        self.slotNNumber.setObjectName("slotNNumber")
        self.slotENumber = QtWidgets.QLabel(self.centralwidget)
        self.slotENumber.setGeometry(QtCore.QRect(482, 349, 16, 16))
        self.slotENumber.setText("")
        self.slotENumber.setAlignment(QtCore.Qt.AlignCenter)
        self.slotENumber.setProperty("value", "")
        self.slotENumber.setObjectName("slotENumber")
        self.slotWNumber = QtWidgets.QLabel(self.centralwidget)
        self.slotWNumber.setGeometry(QtCore.QRect(390, 349, 16, 16))
        self.slotWNumber.setText("")
        self.slotWNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.slotWNumber.setProperty("value", "")
        self.slotWNumber.setObjectName("slotWNumber")
        self.slotCNumber = QtWidgets.QLabel(self.centralwidget)
        self.slotCNumber.setGeometry(QtCore.QRect(436, 349, 16, 16))
        self.slotCNumber.setText("")
        self.slotCNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.slotCNumber.setProperty("value", "")
        self.slotCNumber.setObjectName("slotCNumber")
        self.slotSNumber = QtWidgets.QLabel(self.centralwidget)
        self.slotSNumber.setGeometry(QtCore.QRect(436, 391, 16, 16))
        self.slotSNumber.setText("")
        self.slotSNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.slotSNumber.setProperty("value", "")
        self.slotSNumber.setObjectName("slotSNumber")
        self.userNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.userNameLabel.setGeometry(QtCore.QRect(320, 430, 251, 31))
        self.userNameLabel.setText("")
        self.userNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.userNameLabel.setObjectName("userNameLabel")
        self.opponentCup = QtWidgets.QLabel(self.centralwidget)
        self.opponentCup.setGeometry(QtCore.QRect(373, 50, 151, 141))
        self.opponentCup.setText("")
        self.opponentCup.setPixmap(QtGui.QPixmap(":/newPrefix/opponentCup.png"))
        self.opponentCup.setObjectName("opponentCup")
        self.opponentNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.opponentNameLabel.setGeometry(QtCore.QRect(310, 10, 271, 31))
        self.opponentNameLabel.setText("")
        self.opponentNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.opponentNameLabel.setObjectName("opponentNameLabel")
        self.opponentCurrentDiceNumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.opponentCurrentDiceNumberLabel.setGeometry(QtCore.QRect(417, 91, 61, 61))
        self.opponentCurrentDiceNumberLabel.setStyleSheet("#opponentCurrentDiceNumberLabel{\n"
"    font-size:55px;\n"
"}")
        self.opponentCurrentDiceNumberLabel.setText("")
        self.opponentCurrentDiceNumberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.opponentCurrentDiceNumberLabel.setObjectName("opponentCurrentDiceNumberLabel")
        self.sumScreen = QtWidgets.QLabel(self.centralwidget)
        self.sumScreen.setGeometry(QtCore.QRect(91, 60, 211, 91))
        self.sumScreen.setText("")
        self.sumScreen.setPixmap(QtGui.QPixmap(":/newPrefix/SumScreen.png"))
        self.sumScreen.setObjectName("sumScreen")
        self.sumTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.sumTitleLabel.setGeometry(QtCore.QRect(100, 43, 201, 41))
        self.sumTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sumTitleLabel.setObjectName("sumTitleLabel")
        self.gessTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.gessTitleLabel.setGeometry(QtCore.QRect(90, 270, 201, 41))
        self.gessTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gessTitleLabel.setObjectName("gessTitleLabel")
        self.sendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sendBtn.setEnabled(True)
        self.sendBtn.setGeometry(QtCore.QRect(40, 412, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.sendBtn.setFont(font)
        self.sendBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendBtn.setStyleSheet("#sendBtn {\n"
"  display: inline-block;\n"
"  padding: 15px 25px;\n"
"  font-size: 28px;\n"
"  font-family: Calibri;\n"
"  text-align: center;    \n"
"  text-decoration: none;\n"
"  outline: none;\n"
"  color: #fff;\n"
"  background-color: #70ad46;\n"
"  border: none;\n"
"  border-radius: 15px;\n"
"}\n"
"\n"
"#sendBtn[enabled=\"false\"] {\n"
"  display: inline-block;\n"
"  padding: 15px 25px;\n"
"  font-size: 28px;\n"
"  font-family: Calibri;\n"
"  text-align: center;    \n"
"  text-decoration: none;\n"
"  outline: none;\n"
"  color: #fff;\n"
"  background-color: #a0a0a0;\n"
"  border: none;\n"
"  border-radius: 15px;\n"
"}\n"
"\n"
"#sendBtn:hover {\n"
"background-color: #3e8e41\n"
"}\n"
"\n"
"#sendBtn:pressed {\n"
"  background-color: #4CAF50;\n"
"}\n"
"")
        self.sendBtn.setObjectName("sendBtn")
        self.input0 = QtWidgets.QLineEdit(self.centralwidget)
        self.input0.setGeometry(QtCore.QRect(41, 314, 45, 80))
        self.input0.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input0.setText("")
        self.input0.setAlignment(QtCore.Qt.AlignCenter)
        self.input0.setObjectName("input0")
        self.input1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input1.setGeometry(QtCore.QRect(105, 314, 45, 80))
        self.input1.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input1.setText("")
        self.input1.setAlignment(QtCore.Qt.AlignCenter)
        self.input1.setObjectName("input1")
        self.input2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input2.setGeometry(QtCore.QRect(169, 314, 45, 80))
        self.input2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input2.setText("")
        self.input2.setAlignment(QtCore.Qt.AlignCenter)
        self.input2.setObjectName("input2")
        self.input3 = QtWidgets.QLineEdit(self.centralwidget)
        self.input3.setGeometry(QtCore.QRect(233, 314, 45, 80))
        self.input3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input3.setText("")
        self.input3.setAlignment(QtCore.Qt.AlignCenter)
        self.input3.setObjectName("input3")
        self.input4 = QtWidgets.QLineEdit(self.centralwidget)
        self.input4.setGeometry(QtCore.QRect(297, 314, 45, 80))
        self.input4.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input4.setText("")
        self.input4.setAlignment(QtCore.Qt.AlignCenter)
        self.input4.setObjectName("input4")
        self.sumContainer = QtWidgets.QWidget(self.centralwidget)
        self.sumContainer.setGeometry(QtCore.QRect(100, 90, 201, 71))
        self.sumContainer.setStyleSheet("#sumContainer {\n"
"    background-color: #fff;\n"
"    padding: 15px 25px;\n"
"      border: 1px solid blue;\n"
"      border-radius: 10px;\n"
"}\n"
"")
        self.sumContainer.setObjectName("sumContainer")
        self.sumValueLabel = QtWidgets.QLabel(self.sumContainer)
        self.sumValueLabel.setGeometry(QtCore.QRect(0, 0, 201, 71))
        self.sumValueLabel.setStyleSheet("")
        self.sumValueLabel.setText("")
        self.sumValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sumValueLabel.setObjectName("sumValueLabel")
        self.msgTitle = QtWidgets.QLabel(self.centralwidget)
        self.msgTitle.setGeometry(QtCore.QRect(560, 153, 331, 41))
        self.msgTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.msgTitle.setObjectName("msgTitle")
        self.msgContainer = QtWidgets.QWidget(self.centralwidget)
        self.msgContainer.setGeometry(QtCore.QRect(560, 190, 331, 151))
        self.msgContainer.setStyleSheet("#msgContainer {\n"
"    background-color: #fff;\n"
"    padding: 15px 25px;\n"
"      border: 1px solid black;\n"
"      border-radius: 10px;\n"
"}\n"
"")
        self.msgContainer.setObjectName("msgContainer")
        self.msgLabel = QtWidgets.QLabel(self.msgContainer)
        self.msgLabel.setGeometry(QtCore.QRect(10, 10, 321, 141))
        self.msgLabel.setStyleSheet("#msgLabel{\n"
"    font-size: 14px\n"
"}")
        self.msgLabel.setText("")
        self.msgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.msgLabel.setObjectName("msgLabel")
        self.slotN = QtWidgets.QPushButton(self.centralwidget)
        self.slotN.setEnabled(False)
        self.slotN.setGeometry(QtCore.QRect(428, 299, 31, 31))
        self.slotN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.slotN.setStyleSheet("#slot {\n"
"    background-color: #fff;\n"
"      border: 1px solid black;\n"
"      border-radius: 4px;\n"
"}\n"
"")
        self.slotN.setText("")
        self.slotN.setProperty("value", "")
        self.slotN.setObjectName("slotN")
        self.slotE = QtWidgets.QPushButton(self.centralwidget)
        self.slotE.setEnabled(False)
        self.slotE.setGeometry(QtCore.QRect(474, 341, 31, 31))
        self.slotE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.slotE.setStyleSheet("#slot {\n"
"    background-color: #fff;\n"
"      border: 1px solid black;\n"
"      border-radius: 4px;\n"
"}\n"
"")
        self.slotE.setText("")
        self.slotE.setProperty("value", "")
        self.slotE.setObjectName("slotE")
        self.slotS = QtWidgets.QPushButton(self.centralwidget)
        self.slotS.setEnabled(False)
        self.slotS.setGeometry(QtCore.QRect(428, 383, 31, 31))
        self.slotS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.slotS.setStyleSheet("#slot {\n"
"    background-color: #fff;\n"
"      border: 1px solid black;\n"
"      border-radius: 4px;\n"
"}\n"
"")
        self.slotS.setText("")
        self.slotS.setProperty("value", "")
        self.slotS.setObjectName("slotS")
        self.slotW = QtWidgets.QPushButton(self.centralwidget)
        self.slotW.setEnabled(False)
        self.slotW.setGeometry(QtCore.QRect(382, 341, 31, 31))
        self.slotW.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.slotW.setStyleSheet("#slot {\n"
"    background-color: #fff;\n"
"      border: 1px solid black;\n"
"      border-radius: 4px;\n"
"}\n"
"")
        self.slotW.setText("")
        self.slotW.setProperty("value", "")
        self.slotW.setObjectName("slotW")
        self.slotC = QtWidgets.QPushButton(self.centralwidget)
        self.slotC.setEnabled(False)
        self.slotC.setGeometry(QtCore.QRect(428, 341, 31, 31))
        self.slotC.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.slotC.setStyleSheet("#slot {\n"
"    background-color: #fff;\n"
"      border: 1px solid black;\n"
"      border-radius: 4px;\n"
"}\n"
"")
        self.slotC.setText("")
        self.slotC.setProperty("value", "")
        self.slotC.setObjectName("slotC")
        self.gameNameLabel.raise_()
        self.playerCup.raise_()
        self.userNameLabel.raise_()
        self.opponentCup.raise_()
        self.opponentNameLabel.raise_()
        self.opponentCurrentDiceNumberLabel.raise_()
        self.sumScreen.raise_()
        self.sumTitleLabel.raise_()
        self.gessTitleLabel.raise_()
        self.sendBtn.raise_()
        self.input0.raise_()
        self.input1.raise_()
        self.input2.raise_()
        self.input3.raise_()
        self.input4.raise_()
        self.sumContainer.raise_()
        self.msgTitle.raise_()
        self.msgContainer.raise_()
        self.slotN.raise_()
        self.slotE.raise_()
        self.slotS.raise_()
        self.slotW.raise_()
        self.slotC.raise_()
        self.slotSNumber.raise_()
        self.slotWNumber.raise_()
        self.slotCNumber.raise_()
        self.slotENumber.raise_()
        self.slotNNumber.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kiriki"))
        self.gameNameLabel.setText(_translate("MainWindow", "Kiriki"))
        self.sumTitleLabel.setText(_translate("MainWindow", "Soma"))
        self.gessTitleLabel.setText(_translate("MainWindow", "Aposta"))
        self.sendBtn.setText(_translate("MainWindow", "ENVIAR"))
        self.input0.setInputMask(_translate("MainWindow", "0"))
        self.input1.setInputMask(_translate("MainWindow", "0"))
        self.input2.setInputMask(_translate("MainWindow", "0"))
        self.input3.setInputMask(_translate("MainWindow", "0"))
        self.input4.setInputMask(_translate("MainWindow", "0"))
        self.msgTitle.setText(_translate("MainWindow", "Mensagens"))
from .images import Config_rc
